version: '3.1'
services:
  db:
    image: mongo:4.4.6-bionic
    ports:
      - 27017:27017
    volumes:
      - ./dataset.tsv:/docker-entrypoint-initdb.d/dataset.tsv
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh