[build]
  base = "/"
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 5174
  port = 8888
  publish = "dist"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200